"""
# =============================================================================
# Sample of charts from the trainees survey
# Author: A. Vismara (DG-MF/SRF)
# Created on: 2024-05-20
# Last update on: ...
# =============================================================================

The script creates some helper dictionaries for the other plotting functions
"""

q_cols_order ={
    1: ['0 (not at all likely)', 1,2,3,4,5,6,7,8,9, '10 (extremely likely)'],
    2: False,
    3: False,
    4: ['Analyst (E-E/F)', 'Support functions (A-D)', 'Expert (F-F/G)', 'Lead / Team Lead (H)', 'I cannot say'],
    5: ['Strongly agree', 'Agree', 'I cannot say', "Disagree", 'Strongly Disagree'],
    6: ['strongly agree', 'agree', 'neutral', "disagree", 'strongly disagree', 'cannot say'],
    7: ['on a daily basis', 'on a weekly basis', 'on a biweekly basis', 'on a monthly basis', 'rarely', 'never'],
    8: ['very comfortable', 'comfortable', 'neither comfortable nor uncomfortable','uncomfortable', 'not comfortable at all', 'cannot say'],
    9: ['I have not worked extra hours', '1-2 hours', '3-4 hours', '5-6 hours', '7-8 hours',
        '9-14 hours', '15 hours or more'],
    10: ['Yes, always', 'Yes, most of the time', 'Sometimes, but not frequently', 'Never', 'I cannot say'],
    11: False,
    12: ['Strongly agree', 'Agree', 'I cannot say', 'Disagree', 'Strongly disagree'],
    13: ['very beneficial', 'somewhat beneficial', 'neutral', 'somewhat harmful', 'very harmful'],
    14: ['Never', 'Rarely', 'Sometimes', 'Usually', 'Always'],
    15: ['Strongly disagree', "Disagree", 'Cannot say', 'Agree', 'Strongly agree'],
    16: ['never', 'a few times a year', 'once a month or less', 'a few times a month', 'once a week',
         'a few times a week', 'daily'],
    17: ['Your direct manager in your BA', 'The Director General or Deputy Director General of HR',
         'Another manager', 'Whistleblowing tool', 'None of the above'],
    18: ['very dissatisfied', 'dissatisfied', 'neutral', 'satisfied', 'very satisfied', 'does not apply'],
    19: ['very comfortable', 'Comfortable', 'neutral', 'uncomfortable', 'very uncomfortable', 'did not feel comfortable to disclose it',
         'did not feel it was necessary to disclose it', 'does not apply'],
    20: False,
    21: False,
    22: False,
    23: ['very satisfied', 'satisfied', 'neutral', 'dissatisfied', 'very dissatisfied', 'cannot say'],
    24: False,
    25: ['less than 70 EUR', '70-99 EUR', '100-149 EUR', '150-199 EUR', '200-249 EUR', '250 EUR or more'],
    26: ['less than 15', '15-30', '30-45', '45-60', '60-75', 'more than 75'],
    27: ['Yes, always', 'Yes, more often than not', 'Yes, sometimes', 'No', 'I bring my own food for other reasons (ie dietary requirements)'],
    28: ['never', 'once', 'twice', 'three times', 'four times', 'five times'],
    29: ['never', 'once', 'twice', 'three times', 'four times', 'five times'],
    30: False,
    31: False,
    32: ['very satisfied', 'satisfied', 'neutral', 'dissatisfied', 'very dissatisfied', 'cannot say/not applicable'],
    33: False,
    34: ['Very dissatisfied', 'Somewhat dissatisfied', 'Neutral', 'Somewhat satisfied', 'Very satisfied'],
    35: False,
    36: False,
    37: False,
    38: False,
    39: ['Strongly agree', 'Agree', 'Cannot say', 'Disagree', 'Strongly disagree'],
    40: ['very satisfied', 'satisfied', 'neutral', 'dissatisfied', 'very dissatisfied', 'cannot say'],
    41: ['very beneficial', 'somewhat beneficial', 'neutral', 'somewhat harmful', 'very harmful', 'prefer not to say'],
    42: False,
    43: ['less than a month', '1-3 months', '3-6 months', '6-9 months', '9-12 months'],
    44: False,
    45: False,
    46: False,
    47: False,
    48: False,
    49: False,
    50: False,
}

q_type ={
    1: 'likert',
    2: 'quali',
    3: 'quali',
    4: 'bars',
    5: 'likert',
    6: 'likert',
    7: 'likert',
    8: 'likert',
    9: 'likert',
    10: 'likert',
    11: 'bars',
    12: 'likert',
    13: 'likert',
    14: 'likert',
    15: 'likert',
    16: 'likert',
    17: 'bars',
    18: 'likert',
    19: 'likert',
    20: 'bars',
    21: 'bars',
    22: 'bars',
    23: 'likert',
    24: 'quali',
    25: 'bars',
    26: 'bars',
    27: 'bars',
    28: 'bars',
    29: 'bars',
    30: 'bars',
    31: 'bars',
    32: 'likert',
    33: 'bars',
    34: 'bars',
    35: 'bars',
    36: 'bars',
    37: 'bars',
    38: 'bars',
    39: 'likert',
    40: 'likert',
    41: 'likert',
    42: 'bars',
    43: 'bars',
    44: 'bars',
    45: 'bars',
    46: 'bars',
    47: 'bars',
    48: 'bars',
    49: 'bars',
    50: 'quali',
}
